{"name": "TC4_004: Add Contact with invalid Data via API", "status": "passed", "steps": [{"name": "Step 1: Submit POST request with invalid data", "status": "passed", "start": 1737005042744, "stop": 1737005043758}, {"name": "Step 2: Verify failed  Add Contact", "status": "passed", "attachments": [{"name": "API Response", "source": "a3cccbee-737a-4c48-b7b4-3e6bd0fddda3-attachment.json", "type": "application/json"}], "start": 1737005043758, "stop": 1737005043763}], "attachments": [{"name": "logs", "source": "480774da-da9d-4daf-8ef7-a5cb1f82ddf7-attachment.txt", "type": "text/plain"}], "start": 1737005042744, "stop": 1737005043764, "uuid": "4d8bb06c-d267-40cb-93c3-a569314044da", "historyId": "e090cec3a16a1241e57392887e0922f4", "testCaseId": "e090cec3a16a1241e57392887e0922f4", "fullName": "tests.api.test_add_contact_via_api.TestAddContactFunctionality#test_verify_if_the_api_handles_invalid_contact_data", "labels": [{"name": "subSuite", "value": "TC4_004: Add Contact with invalid Data via API"}, {"name": "parentSuite", "value": "Regression"}, {"name": "severity", "value": "normal"}, {"name": "suite", "value": "Contact Management Functionality"}, {"name": "feature", "value": "Contact Management Functionality"}, {"name": "tag", "value": "tags('api_management_functionality')"}, {"name": "host", "value": "CHEQ-J7M1HB3"}, {"name": "thread", "value": "11780-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.api.test_add_contact_via_api"}]}