{"name": "TC7_004: Verify edit contact with invalid data via the API", "status": "passed", "attachments": [{"name": "API Response", "source": "da91fe56-3a05-4cc6-8ea7-7f4c3fd6654b-attachment.json", "type": "application/json"}, {"name": "API Response", "source": "d5ea4389-b9cb-4423-888e-48162cd8daf7-attachment.json", "type": "application/json"}, {"name": "log", "source": "f85333b8-12bb-4b07-b564-294d3dd632bb-attachment.txt", "type": "text/plain"}], "start": 1736758030192, "stop": 1736758032378, "uuid": "214a602d-3e44-4aa5-a65f-4b4034aca54a", "historyId": "ed9d7f2f45e41e5e732be277ba556c2b", "testCaseId": "ed9d7f2f45e41e5e732be277ba556c2b", "fullName": "tests.api.test_edit_contact_via_api.TestContactEditFunctionality#test_verify_if_the_api_fails_when_editing_a_contact_with_invalid_data", "labels": [{"name": "parentSuite", "value": "Regression"}, {"name": "severity", "value": "normal"}, {"name": "subSuite", "value": "TC7_004: Verify edit contact with invalid data via the API"}, {"name": "suite", "value": "Contact Edit Functionality"}, {"name": "feature", "value": "Contact Edit Functionality"}, {"name": "tag", "value": "tags('api_edit_functionality')"}, {"name": "host", "value": "CHEQ-J7M1HB3"}, {"name": "thread", "value": "14480-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.api.test_edit_contact_via_api"}]}