{"name": "TC4_004: Add Contact with invalid Data via API", "status": "passed", "steps": [{"name": "Step 1: Submit POST request with invalid data", "status": "passed", "start": 1738081449942, "stop": 1738081450914}, {"name": "Step 2: Verify failed  Add Contact", "status": "passed", "attachments": [{"name": "API Response", "source": "cb4d64a7-f6ce-411d-89f9-07cdb157805e-attachment.json", "type": "application/json"}], "start": 1738081450914, "stop": 1738081450917}], "attachments": [{"name": "log", "source": "8b87fc8d-810a-4932-8729-0f594276417b-attachment.txt", "type": "text/plain"}], "start": 1738081449942, "stop": 1738081450917, "uuid": "1a1d6213-9ee2-4d2d-bdf5-b5078cde832f", "historyId": "e090cec3a16a1241e57392887e0922f4", "testCaseId": "e090cec3a16a1241e57392887e0922f4", "fullName": "tests.api.test_add_contact_via_api.TestAddContactFunctionality#test_verify_if_the_api_handles_invalid_contact_data", "labels": [{"name": "suite", "value": "Contact Management Functionality"}, {"name": "feature", "value": "Contact Management Functionality"}, {"name": "parentSuite", "value": "Regression"}, {"name": "severity", "value": "normal"}, {"name": "subSuite", "value": "TC4_004: Add Contact with invalid Data via API"}, {"name": "tag", "value": "tags('api_management_functionality')"}, {"name": "host", "value": "CHEQ-J7M1HB3"}, {"name": "thread", "value": "7708-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.api.test_add_contact_via_api"}]}