{"name": "TC3_004: Log In with invalid credentials via API", "status": "passed", "steps": [{"name": "Step 1: Send POST request with invalid data ", "status": "passed", "steps": [{"name": "Step 2: Verify failed Login.", "status": "passed", "attachments": [{"name": "API Response", "source": "3df479db-78be-4a32-abaa-1793e8b2795c-attachment.json", "type": "application/json"}], "start": 1737988732714, "stop": 1737988733786}], "start": 1737988732714, "stop": 1737988733786}], "attachments": [{"name": "log", "source": "63ef5ad4-b853-4df5-aacc-6cd85e1e120c-attachment.txt", "type": "text/plain"}], "start": 1737988732714, "stop": 1737988733786, "uuid": "de05d141-0f09-4cc9-9b8d-f624c4ba0a04", "historyId": "a2e24d3ae71a71bded3f9b0fe945fbb7", "testCaseId": "a2e24d3ae71a71bded3f9b0fe945fbb7", "fullName": "tests.api.test_login_via_api.TestUserLoginFunctionality#test_failed_login_via_api", "labels": [{"name": "severity", "value": "normal"}, {"name": "suite", "value": "User Login Functionality"}, {"name": "feature", "value": "User Login Functionality"}, {"name": "parentSuite", "value": "Regression"}, {"name": "subSuite", "value": "TC3_004: Log In with invalid credentials via API"}, {"name": "tag", "value": "tags('api_login_functionality')"}, {"name": "host", "value": "CHEQ-J7M1HB3"}, {"name": "thread", "value": "13628-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.api.test_login_via_api"}]}