{"name": "TC4_004: Verify add contact with invalid data via API", "status": "passed", "attachments": [{"name": "API Response", "source": "17376cf0-da2b-423b-acc9-06c2af149d5c-attachment.json", "type": "application/json"}, {"name": "log", "source": "77e0e7e9-20a6-4181-997a-b93ef55fdd05-attachment.txt", "type": "text/plain"}], "start": 1736758018345, "stop": 1736758019456, "uuid": "14faff89-98b6-4899-b24d-aafbbb8b101c", "historyId": "e090cec3a16a1241e57392887e0922f4", "testCaseId": "e090cec3a16a1241e57392887e0922f4", "fullName": "tests.api.test_add_contact_via_api.TestAddContactFunctionality#test_verify_if_the_api_handles_invalid_contact_data", "labels": [{"name": "parentSuite", "value": "Regression"}, {"name": "feature", "value": "Contact Management Functionality"}, {"name": "severity", "value": "normal"}, {"name": "suite", "value": "Contact Management Functionality"}, {"name": "subSuite", "value": "TC4_004: Verify add contact with invalid data via API"}, {"name": "tag", "value": "tags('api_management_functionality')"}, {"name": "host", "value": "CHEQ-J7M1HB3"}, {"name": "thread", "value": "14480-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.api.test_add_contact_via_api"}]}