[32mINFO    [0m pytest_logger:log_util.py:49 Test data file found and loaded
[31m[1mERROR   [0m pytest_logger:log_util.py:53 An error occurred during the POST request.