{"name": "TC4_003: Verify add contact with invalid data via API", "status": "passed", "attachments": [{"name": "API Response", "source": "9cc03ebe-3ae1-4809-a240-85a84d47c43a-attachment.json", "type": "application/json"}, {"name": "log", "source": "ee32e355-e13c-4ff0-addf-06bc3ad117ed-attachment.txt", "type": "text/plain"}], "start": 1736758016209, "stop": 1736758017298, "uuid": "fdcc7968-3897-4220-a375-7e2c6cb625c0", "historyId": "6ce402479b8f163afd34bc2b1478a4c6", "testCaseId": "6ce402479b8f163afd34bc2b1478a4c6", "fullName": "tests.api.test_add_contact_via_api.TestAddContactFunctionality#test_add_contact_with_valid_data_via_the_api", "labels": [{"name": "parentSuite", "value": "Regression"}, {"name": "feature", "value": "Contact Management Functionality"}, {"name": "severity", "value": "normal"}, {"name": "suite", "value": "Contact Management Functionality"}, {"name": "subSuite", "value": "TC4_003: Verify add contact with invalid data via API"}, {"name": "tag", "value": "tags('api_management_functionality')"}, {"name": "host", "value": "CHEQ-J7M1HB3"}, {"name": "thread", "value": "14480-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.api.test_add_contact_via_api"}]}