{"name": "TC4_001: Add Contact with valid Data via UI", "status": "failed", "statusDetails": {"message": "Failed: Element with locator ('css selector', '#email') is not visible within the timeout period", "trace": "self = <utils.element_wait_util.ElementWaitUtil object at 0x00000134469F9C50>, locator = ('css selector', '#email')\n\n    def wait_element_to_be_visible(self, locator):\n        \"\"\"Wait for the element to be visible.\"\"\"\n        try:\n            element = WebDriverWait(self.driver, config_reader.get_value\n>           ('settings', 'element_visibility_timeout')).until(\n                EC.visibility_of_element_located(locator)\n            )\n\nutils\\element_wait_util.py:23: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"21ae419b30dc19a9d3a7eba72b113948\")>, method = <function visibility_of_element_located.<locals>._predicate at 0x0000013446A6DC60>\nmessage = ''\n\n    def until(self, method: Callable[[D], Union[Literal[False], T]], message: str = \"\") -> T:\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value does not evaluate to ``False``.\n    \n        :param method: callable(WebDriver)\n        :param message: optional message for :exc:`TimeoutException`\n        :returns: the result of the last call to `method`\n        :raises: :exc:`selenium.common.exceptions.TimeoutException` if timeout occurs\n        \"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.monotonic() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, \"screen\", None)\n                stacktrace = getattr(exc, \"stacktrace\", None)\n            if time.monotonic() > end_time:\n                break\n            time.sleep(self._poll)\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message: \nE       Stacktrace:\nE       \tGetHandleVerifier [0x00DE74A3+25091]\nE       \t(No symbol) [0x00D6DC04]\nE       \t(No symbol) [0x00C4B373]\nE       \t(No symbol) [0x00C8F4DC]\nE       \t(No symbol) [0x00C8F65B]\nE       \t(No symbol) [0x00CCD8E2]\nE       \t(No symbol) [0x00CB1F54]\nE       \t(No symbol) [0x00CCB49E]\nE       \t(No symbol) [0x00CB1CA6]\nE       \t(No symbol) [0x00C831D5]\nE       \t(No symbol) [0x00C8435D]\nE       \tGetHandleVerifier [0x010E07C3+3142947]\nE       \tGetHandleVerifier [0x010F1A2B+3213195]\nE       \tGetHandleVerifier [0x010EC412+3191154]\nE       \tGetHandleVerifier [0x00E88720+685184]\nE       \t(No symbol) [0x00D76E1D]\nE       \t(No symbol) [0x00D73E18]\nE       \t(No symbol) [0x00D73FB6]\nE       \t(No symbol) [0x00D666F0]\nE       \tBaseThreadInitThunk [0x762E5D49+25]\nE       \tRtlInitializeExceptionChain [0x76FCBD6B+107]\nE       \tRtlGetAppContainerNamedObjectPath [0x76FCBCF1+561]\n\n.venv\\Lib\\site-packages\\selenium\\webdriver\\support\\wait.py:105: TimeoutException\n\nDuring handling of the above exception, another exception occurred:\n\nself = <test_add_contact_via_ui.TestContactManagementFunctionality object at 0x000001344647B4D0>\n\n    @AddContact.add_contact_decorators_tc4_001_ui\n    def test_add_contact_with_valid_data_via_ui(self):\n        data = DataGenerator().generate_valid_add_contact_data()\n>       with AllureStepWithAttachment(self.driver, \"Step 1: Login to Contact List App\"):\n\ntests\\ui\\test_add_contact_via_ui.py:27: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nutils\\allure_util.py:66: in __exit__\n    raise exc_val\ntests\\ui\\test_add_contact_via_ui.py:28: in test_add_contact_with_valid_data_via_ui\n    self.signup.login_with_valid_data()\ntests\\reusable\\reusable_scripts.py:38: in login_with_valid_data\n    self.login_page.enter_email(login_email)\npages\\login_page.py:22: in enter_email\n    self.element_keyboard_input_util.input_element(self.EMAIL_TXT, email)\nutils\\element_keyboard_input_util.py:17: in input_element\n    element = self.wait_util.wait_element_to_be_visible(locator)\nutils\\element_wait_util.py:29: in wait_element_to_be_visible\n    self.reporter.results_reporter(TIMEOUT_EXCEPTION_ERROR_MESSAGE, \"error\", locator=locator)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <utils.reporter_util.ReporterUtil object at 0x00000134469FF120>, log_message = 'Element with locator {locator} is not visible within the timeout period', log_level = 'error'\nkwargs = {'locator': ('css selector', '#email')}\ncurrent_test = {'test_class': 'TestContactManagementFunctionality', 'test_file': 'test_add_contact_via_ui.py', 'test_function': 'test_add_contact_with_valid_data_via_ui'}\ntest_file = 'test_add_contact_via_ui.py', test_function = 'test_add_contact_with_valid_data_via_ui', test_scenario_name = 'Test Add Contact Via Ui', test_case_name = 'Add Contact With Valid Data Via Ui'\ncapture_screenshot = 'Yes', screenshot_name = 'screenshot_01292025_172326986'\n\n    def results_reporter(self, log_message, log_level=\"info\", **kwargs):\n        current_test = get_current_test_info()\n        test_file = current_test.get('test_file')\n        test_function = current_test.get('test_function')\n        test_scenario_name = test_file.replace(\"tests\", \"\").replace(\".py\", \" \").replace(\"_\", \" \").strip().title()\n        test_case_name = test_function.replace(\"test\", \"\").replace(\"_\", \" \").strip().title()\n        capture_screenshot = config_reader.get_value(\"screenshot_settings\", \"capture_screenshot\")\n        screenshot_name = self.get_screenshot_datetime()\n        # Passed if log_level = info\n        if log_level == \"info\":\n    \n            log.get_log_formatted_message(log_message, log_level, **kwargs)\n            if capture_screenshot == \"Yes\":\n                screenshot.save_screenshot(self.driver,test_scenario_name, test_case_name, screenshot_name)\n        else:\n            # Failed if log_level = warning, error, debug or critical\n            screenshot.save_screenshot(self.driver,test_scenario_name, test_case_name, screenshot_name)\n            if capture_screenshot == \"Yes\":\n                screenshot.save_screenshot(self.driver,test_scenario_name, test_case_name, screenshot_name)\n>           pytest.fail(log.get_log_formatted_message(log_message, log_level, **kwargs))\nE           Failed: Element with locator ('css selector', '#email') is not visible within the timeout period\n\nutils\\reporter_util.py:37: Failed"}, "steps": [{"name": "Step 1: Login to Contact List App", "status": "failed", "statusDetails": {"message": "Failed: Element with locator ('css selector', '#email') is not visible within the timeout period\n", "trace": "  File \"C:\\Users\\SandroJimena\\PycharmProjects\\Contact_List_App_Selenium_Python\\tests\\ui\\test_add_contact_via_ui.py\", line 28, in test_add_contact_with_valid_data_via_ui\n    self.signup.login_with_valid_data()\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File \"C:\\Users\\SandroJimena\\PycharmProjects\\Contact_List_App_Selenium_Python\\tests\\reusable\\reusable_scripts.py\", line 38, in login_with_valid_data\n    self.login_page.enter_email(login_email)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^\n  File \"C:\\Users\\SandroJimena\\PycharmProjects\\Contact_List_App_Selenium_Python\\pages\\login_page.py\", line 22, in enter_email\n    self.element_keyboard_input_util.input_element(self.EMAIL_TXT, email)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\SandroJimena\\PycharmProjects\\Contact_List_App_Selenium_Python\\utils\\element_keyboard_input_util.py\", line 17, in input_element\n    element = self.wait_util.wait_element_to_be_visible(locator)\n  File \"C:\\Users\\SandroJimena\\PycharmProjects\\Contact_List_App_Selenium_Python\\utils\\element_wait_util.py\", line 29, in wait_element_to_be_visible\n    self.reporter.results_reporter(TIMEOUT_EXCEPTION_ERROR_MESSAGE, \"error\", locator=locator)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\SandroJimena\\PycharmProjects\\Contact_List_App_Selenium_Python\\utils\\reporter_util.py\", line 37, in results_reporter\n    pytest.fail(log.get_log_formatted_message(log_message, log_level, **kwargs))\n    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\SandroJimena\\PycharmProjects\\Contact_List_App_Selenium_Python\\.venv\\Lib\\site-packages\\_pytest\\outcomes.py\", line 178, in fail\n    raise Failed(msg=reason, pytrace=pytrace)\n"}, "attachments": [{"name": "image_on_failure", "source": "a7d49154-94f5-4838-9885-012a5ed418d0-attachment.png", "type": "image/png"}], "start": 1738142591670, "stop": 1738142607301}], "attachments": [{"name": "log", "source": "a3c9bf56-766c-4bc4-b41e-5cb7e69df954-attachment.txt", "type": "text/plain"}], "start": 1738142591666, "stop": 1738142607311, "uuid": "fa88732e-d6e9-422e-bd9a-554561330e40", "historyId": "366a79fa101824aacdb9e8ea35011a0b", "testCaseId": "366a79fa101824aacdb9e8ea35011a0b", "fullName": "tests.ui.test_add_contact_via_ui.TestContactManagementFunctionality#test_add_contact_with_valid_data_via_ui", "labels": [{"name": "feature", "value": "Contact Management Functionality"}, {"name": "suite", "value": "Contact Management Functionality"}, {"name": "severity", "value": "normal"}, {"name": "subSuite", "value": "TC4_001: Add Contact with valid Data via UI"}, {"name": "parentSuite", "value": "Regression"}, {"name": "tag", "value": "tags('ui_management_functionality')"}, {"name": "host", "value": "CHEQ-J7M1HB3"}, {"name": "thread", "value": "18864-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.ui.test_add_contact_via_ui"}]}