{"name": "TC1_001: Verify signup_with_invalid_data via UI", "status": "passed", "steps": [{"name": "Step 1: Signup to Contact List App with invalid Data", "status": "passed", "attachments": [{"name": "image", "source": "48c2c83e-6a91-4949-b694-89612f370214-attachment.png", "type": "image/png"}], "start": 1736758228297, "stop": 1736758230818}, {"name": "Step 2: Verify Failed Signup", "status": "passed", "attachments": [{"name": "image", "source": "c6f389b6-8035-40a6-a0e1-2e1ce59e04a9-attachment.png", "type": "image/png"}], "start": 1736758230818, "stop": 1736758231903}], "attachments": [{"name": "log", "source": "a34e453b-daea-4ac4-af8f-29eb262f1b23-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "user", "value": "{'firstName': '', 'lastName': 'Jimenix', 'email': 'Jimenix@example.com', 'password': '12345qwert', 'result': 'User validation failed: firstName: Path `firstName` is required.'}"}], "start": 1736758228296, "stop": 1736758231904, "uuid": "bafa5c8e-b2e8-46b3-bda6-ccc71ce8b9bd", "historyId": "33c8df89c162603a2b455eeeec8f0ed0", "testCaseId": "6509c706c67decc84e09c503a9c6463f", "fullName": "tests.ui.test_signup_via_ui.TestUserSignupFunctionality#test_signup_with_invalid_data_via_ui", "labels": [{"name": "parentSuite", "value": "Regression"}, {"name": "suite", "value": "User SignUp Functionality"}, {"name": "severity", "value": "normal"}, {"name": "subSuite", "value": "TC1_001: Verify signup_with_invalid_data via UI"}, {"name": "feature", "value": "User SignUp Functionality"}, {"name": "tag", "value": "tags('UI_SignUp_functionality')"}, {"name": "host", "value": "CHEQ-J7M1HB3"}, {"name": "thread", "value": "14480-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.ui.test_signup_via_ui"}]}